# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/14272639-8c08ee7b-b1c2-4e28-9696-6c8329f92704?apikey=PMAK-61683d1b5669aa0046011479-960ef5f1a6018fae39884e5cc4a86c1f9b
          additional-options: reporter htmlextra


workflows:
  say-hello-workflow:
    jobs:
      - newman-collection-run